spring.application.name=binanceBackend

# Reads from environment variables BINANCE_API_KEY and BINANCE_API_SECRET
binance.api.key=${BINANCE_API_KEY:default_dummy_key}
binance.api.secret=${BINANCE_API_SECRET:default_dummy_secret}