spring.application.name=binanceBackend

# Reads from environment variables BINANCE_API_KEY and BINANCE_API_SECRET
binance.api.key=${BINANCE_API_KEY:Y9L1xaet2NesvWD8m9ZmYjQccXJB6XzZN17qesLZmizxkUBXLHJJFcV3V94WT6bz}
binance.api.secret=${BINANCE_API_SECRET:CudQGqSEigPA0uWEdG0IpsVOewUQMrTMX2Pvn4Dwsmv7d2oOdQvaVnyBELWo9kzR}

bybit.api.key=gNuThJhBiO6BB9u8kH
bybit.api.secret=F8iEop8PAqxqIhOxcRW3mnTfijx0JRTj6vri