spring.application.name=binanceBackend

# Fallbacks added for Maven Test phases
binance.api.key=${BINANCE_API_KEY:dummy_key_for_testing}
binance.api.secret=${BINANCE_API_SECRET:dummy_secret_for_testing}

bybit.api.key=${BYBIT_API_KEY:dummy_key_for_testing}
bybit.api.secret=${BYBIT_API_SECRET:dummy_secret_for_testing}


# Futures Keys
binance.futures.api.key=${BINANCE_FUTURES_KEY:dummy_key_for_testing}
binance.futures.api.secret=${BINANCE_FUTURES_SECRET:dummy_secret_for_testing}

#Keys Ankit Demo website Keys 
# binance.api.key=${BINANCE_API_KEY:Y9L1xaet2NesvWD8m9ZmYjQccXJB6XzZN17qesLZmizxkUBXLHJJFcV3V94WT6bz}
# binance.api.secret=${BINANCE_API_SECRET:CudQGqSEigPA0uWEdG0IpsVOewUQMrTMX2Pvn4Dwsmv7d2oOdQvaVnyBELWo9kzR}









# GEMINI_API_KEY=your_gemini_api_key_here
# BINANCE_API_KEY=aOcYuMBNnM6TAbqUsskLN2RsK5XQUQD4RVEmOMPirdADI6f6lmVdqY4uKqtEyMHT
# BINANCE_API_SECRET=y1NZrYzO3molJktfGzguHP608l7FqVc37wRThXZ3qsNU8nfb5sG6yWWeeDPc5tGo
# GOOGLE_GENAI_API_KEY=